services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devcontainer
    ports:
      - "2222:22"
    volumes:
      - .:/workspace
    working_dir: /workspace
    restart: unless-stopped